import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/app/components/theme-provider'
import './globals.css'
import Header from '@/app/components/header'
import { Toaster } from '@/app/components/ui/toaster'
import AppProvider from '@/app/AppProvider'
import { cookies } from 'next/headers'
import Footer from './components/footer'

const inter = Inter({ subsets: ['vietnamese'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = cookies()
  const sessionToken = cookieStore.get('sessionToken')
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <Toaster />
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <AppProvider inititalSessionToken={sessionToken?.value}>
            {children}
          </AppProvider>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}